export const masks = [
  // ბილიკი იწყება /Photos/-ით, რადგან ფოლდერი public-შია.
  { id: 1, name: "ანონიმუსი", price: 15, img: "/Photos/1.png" },
  { id: 2, name: "ჰალკი", price: 12, img: "/Photos/2.png" },
  { id: 3, name: "მეკობრე", price: 12, img: "/Photos/3.png" },
  { id: 4, name: "კივილი", price: 10, img: "/Photos/4.png" },
  { id: 5, name: "კაპიტან ამერიკა", price: 12, img: "/Photos/5.png" },
  { id: 6, name: "ეშმაკი", price: 35, img: "/Photos/6.png" },
  { id: 7, name: "კუნინძა", price: 12, img: "/Photos/7.png" },
  { id: 8, name: "ჯოკერი", price: 35, img: "/Photos/22.png" },
  { id: 9, name: "კლოუნი", price: 35, img: "/Photos/8.png" },
  { id: 10, name: "ნიღაბი", price: 30, img: "/Photos/9.png" },
  { id: 11, name: "კივილი", price: 10, img: "/Photos/10.png" },
  { id: 12, name: "მომო", price: 35, img: "/Photos/11.png" },
  { id: 13, name: "ნიღაბი", price: 20, img: "/Photos/12.png" },
  { id: 14, name: "კლოუნი", price: 35, img: "/Photos/13.png" },
  { id: 15, name: "ჰანიბალი", price: 25, img: "/Photos/14.png" },
  { id: 16, name: "სალვადორ დალი", price: 35, img: "/Photos/15.png" },
  { id: 17, name: "ადამიანი ობობა", price: 12, img: "/Photos/16.png" },
  { id: 18, name: "ანონიმუსი", price: 15, img: "/Photos/log1.png" },
  { id: 19, name: "ზომბი", price: 70, img: "/Photos/25.png" },
  { id: 20, name: "ნიღაბი", price: 12, img: "/Photos/17.png" },
  { id: 21, name: "ნიღაბი", price: 12, img: "/Photos/18.png" },
  { id: 22, name: "ნიღაბი", price: 12, img: "/Photos/19.png" },
  { id: 23, name: "ნიღაბი", price: 12, img: "/Photos/20.png" },
  { id: 24, name: "ნიღაბი", price: 12, img: "/Photos/21.png" },
];